/**
 * Generated by the shadcn CLI, then pointed at the project's configured merger.
 *
 * The CLI writes `export { cn } from "cn"`, which uses the merger's default theme and silently
 * strips colour classes that collide with this project's custom `text-*` scale. See src/lib/cn.ts.
 * If the CLI regenerates this file, restore the re-export below.
 */
export { cn } from "@/lib/cn";
