import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import jsxA11y from "eslint-plugin-jsx-a11y";

// eslint-config-next already registers the jsx-a11y plugin, so re-adding its flat config
// throws "Cannot redefine plugin". Take the recommended rule set only and raise every rule the
// plugin actually enables to error: WCAG 2.2 AA is a non-negotiable in CLAUDE.md, so a11y
// findings must fail the build. Rules the plugin ships as "off" stay off; they are off because
// they cannot see a label passed through a component boundary and fire on correct markup.
const severityOf = (setting) => (Array.isArray(setting) ? setting[0] : setting);
const a11yRules = Object.fromEntries(
  Object.entries(jsxA11y.flatConfigs.recommended.rules ?? {})
    .filter(([, setting]) => severityOf(setting) !== "off" && severityOf(setting) !== 0)
    .map(([rule, setting]) => [
      rule,
      Array.isArray(setting) ? ["error", ...setting.slice(1)] : "error",
    ]),
);

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      ...a11yRules,
      "jsx-a11y/label-has-associated-control": ["error", { assert: "either", depth: 3 }],
      "jsx-a11y/no-autofocus": "error",
      // Deprecated by the plugin in favour of label-has-associated-control.
      "jsx-a11y/label-has-for": "off",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
    },
  },
  {
    // Generated by the shadcn CLI and regenerated rather than hand-edited (CLAUDE.md rule 9).
    files: ["src/components/ui/**"],
    rules: {
      "jsx-a11y/heading-has-content": "off",
      "jsx-a11y/anchor-has-content": "off",
      "jsx-a11y/label-has-associated-control": "off",
      "@typescript-eslint/consistent-type-imports": "off",
    },
  },
  globalIgnores([
    ".next/**",
    // Scratch scripts written by the Playwright MCP during a review run; not project source.
    ".playwright-mcp/**",
    "out/**",
    "build/**",
    // `sanity deploy` builds the hosted Studio here: bundled React and styled-components, about
    // 1,300 warnings of minified vendor code that is gitignored and never edited. Linting a
    // build artefact buries the warnings that matter.
    "dist/**",
    ".sanity/**",
    "next-env.d.ts",
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
