"use client";

// Client: it decides when to inject a third-party script, based on consent and on interaction.

import { useEffect, useState } from "react";
import Script from "next/script";
import { useConsent } from "@/lib/consent";
import { track } from "@/lib/analytics/events";

interface AnalyticsProps {
  gtmId?: string;
  metaPixelId?: string;
}

/**
 * Loads Google Tag Manager and the Meta Pixel, late.
 *
 * Two gates, and both have to open:
 *
 * 1. **Consent.** Nothing loads until the reader has answered the banner, or has answered it on a
 *    previous visit. Consent mode v2 defaults everything to `denied` in the document head, so even
 *    the container's own page view is withheld until the update.
 * 2. **Idle or interaction.** Even after consent, the container waits for the browser to be idle
 *    or for the first scroll or tap. GTM plus GA4 plus the pixel is roughly 120KB of script; on a
 *    64%-mobile audience on Indian networks, letting that compete with the hero for bandwidth is a
 *    Lighthouse score and a real second of LCP.
 *
 * Nothing here throws when an id is absent. `dataLayer` is still pushed by `track()`, so a site
 * with no container id behaves identically minus the reporting, which is what makes the local and
 * CI runs quiet.
 */
export function Analytics({ gtmId, metaPixelId }: AnalyticsProps) {
  const consent = useConsent();
  const [ready, setReady] = useState(false);

  const granted = consent === "accepted";

  useEffect(() => {
    if (!granted || ready) return;

    let cancelled = false;
    const go = (): void => {
      if (!cancelled) setReady(true);
    };

    /*
     * requestIdleCallback where it exists, a timeout where it does not (Safari before 16.4, which
     * is still a real share of Indian iPhones). Either way the first interaction wins, because
     * somebody who has started scrolling has already had their first paint.
     */
    const idle =
      typeof window.requestIdleCallback === "function"
        ? window.requestIdleCallback(go, { timeout: 4000 })
        : window.setTimeout(go, 2500);

    const events: (keyof WindowEventMap)[] = ["scroll", "pointerdown", "keydown"];
    for (const event of events) {
      window.addEventListener(event, go, { once: true, passive: true });
    }

    return () => {
      cancelled = true;
      if (typeof window.cancelIdleCallback === "function" && typeof idle === "number") {
        window.cancelIdleCallback(idle);
      }
      window.clearTimeout(idle as number);
      for (const event of events) window.removeEventListener(event, go);
    };
  }, [granted, ready]);

  if (!granted || !ready) return null;

  return (
    <>
      {gtmId && (
        <Script
          id="gtm"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});
var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${gtmId}');`.trim(),
          }}
        />
      )}

      {/*
        The Meta Pixel is loaded directly rather than through a GTM tag.
        It shares an `event_id` with the server-side Conversions API call for deduplication, and
        that id is generated by this application: routing it through a container would mean the
        academy could break deduplication by editing a tag, and would double the number of places
        the pairing has to stay correct.
      */}
      {metaPixelId && (
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init','${metaPixelId}');
fbq('track','PageView');`.trim(),
          }}
        />
      )}
    </>
  );
}

/**
 * Reports a consent choice to the dataLayer, once, from wherever the banner lives.
 *
 * Separate from the banner so the banner stays a presentational component and this stays testable:
 * the dataLayer assertion in the suite looks for exactly this event.
 */
export function trackConsentChoice(granted: boolean): void {
  track("consent_update", { consent_analytics: granted, consent_marketing: granted });
}
